// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveAIInstancesByProvider = `-- name: CountActiveAIInstancesByProvider :one
select count(*) from ai_service_instances i
join ai_services s on s.id = i.service_id
where s.provider_id = $1 and i.status in ('active', 'suspended')
`

func (q *Queries) CountActiveAIInstancesByProvider(ctx context.Context, providerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAIInstancesByProvider, providerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAIAccessPolicy = `-- name: CreateAIAccessPolicy :one
insert into ai_access_policies (name, tenant_id, rules, status)
values ($1, $2, $3, $4)
returning id, name, tenant_id, rules, status, created_at, updated_at
`

type CreateAIAccessPolicyParams struct {
	Name     string      `json:"name"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Rules    []byte      `json:"rules"`
	Status   string      `json:"status"`
}

func (q *Queries) CreateAIAccessPolicy(ctx context.Context, arg CreateAIAccessPolicyParams) (AiAccessPolicy, error) {
	row := q.db.QueryRow(ctx, createAIAccessPolicy,
		arg.Name,
		arg.TenantID,
		arg.Rules,
		arg.Status,
	)
	var i AiAccessPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TenantID,
		&i.Rules,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAIAuditEvent = `-- name: CreateAIAuditEvent :one
insert into ai_audit_events (actor, tenant_id, subject_type, subject_id, action, message, fields)
values ($1, $2, $3, $4, $5, $6, $7)
returning id, actor, tenant_id, subject_type, subject_id, action, message, fields, created_at
`

type CreateAIAuditEventParams struct {
	Actor       string      `json:"actor"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	SubjectType string      `json:"subject_type"`
	SubjectID   pgtype.UUID `json:"subject_id"`
	Action      string      `json:"action"`
	Message     string      `json:"message"`
	Fields      []byte      `json:"fields"`
}

func (q *Queries) CreateAIAuditEvent(ctx context.Context, arg CreateAIAuditEventParams) (AiAuditEvent, error) {
	row := q.db.QueryRow(ctx, createAIAuditEvent,
		arg.Actor,
		arg.TenantID,
		arg.SubjectType,
		arg.SubjectID,
		arg.Action,
		arg.Message,
		arg.Fields,
	)
	var i AiAuditEvent
	err := row.Scan(
		&i.ID,
		&i.Actor,
		&i.TenantID,
		&i.SubjectType,
		&i.SubjectID,
		&i.Action,
		&i.Message,
		&i.Fields,
		&i.CreatedAt,
	)
	return i, err
}

const createAIBudget = `-- name: CreateAIBudget :one
insert into ai_budgets (tenant_id, scope, scope_ref, limit_usd, period, soft_threshold_pct, hard_threshold_pct)
values ($1, $2, $3, $4, $5, $6, $7)
returning id, tenant_id, scope, scope_ref, limit_usd, period, soft_threshold_pct, hard_threshold_pct, created_at, updated_at
`

type CreateAIBudgetParams struct {
	TenantID         pgtype.UUID `json:"tenant_id"`
	Scope            string      `json:"scope"`
	ScopeRef         string      `json:"scope_ref"`
	LimitUsd         float64     `json:"limit_usd"`
	Period           string      `json:"period"`
	SoftThresholdPct int32       `json:"soft_threshold_pct"`
	HardThresholdPct int32       `json:"hard_threshold_pct"`
}

func (q *Queries) CreateAIBudget(ctx context.Context, arg CreateAIBudgetParams) (AiBudget, error) {
	row := q.db.QueryRow(ctx, createAIBudget,
		arg.TenantID,
		arg.Scope,
		arg.ScopeRef,
		arg.LimitUsd,
		arg.Period,
		arg.SoftThresholdPct,
		arg.HardThresholdPct,
	)
	var i AiBudget
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Scope,
		&i.ScopeRef,
		&i.LimitUsd,
		&i.Period,
		&i.SoftThresholdPct,
		&i.HardThresholdPct,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAIProvider = `-- name: CreateAIProvider :one
insert into ai_providers (name, type, config, tenant_id)
values ($1, $2, $3, $4)
returning id, name, type, config, status, tenant_id, created_at, updated_at
`

type CreateAIProviderParams struct {
	Name     string      `json:"name"`
	Type     string      `json:"type"`
	Config   []byte      `json:"config"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) CreateAIProvider(ctx context.Context, arg CreateAIProviderParams) (AiProvider, error) {
	row := q.db.QueryRow(ctx, createAIProvider,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.TenantID,
	)
	var i AiProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Status,
		&i.TenantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAIProviderCredential = `-- name: CreateAIProviderCredential :one
insert into ai_provider_credentials (provider_id, secret_ref, scopes)
values ($1, $2, $3)
returning id, provider_id, secret_ref, scopes, rotation_due_at, last_validated_at, last_validation_status, created_at
`

type CreateAIProviderCredentialParams struct {
	ProviderID uuid.UUID `json:"provider_id"`
	SecretRef  string    `json:"secret_ref"`
	Scopes     []string  `json:"scopes"`
}

func (q *Queries) CreateAIProviderCredential(ctx context.Context, arg CreateAIProviderCredentialParams) (AiProviderCredential, error) {
	row := q.db.QueryRow(ctx, createAIProviderCredential, arg.ProviderID, arg.SecretRef, arg.Scopes)
	var i AiProviderCredential
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.SecretRef,
		&i.Scopes,
		&i.RotationDueAt,
		&i.LastValidatedAt,
		&i.LastValidationStatus,
		&i.CreatedAt,
	)
	return i, err
}

const createAIQuota = `-- name: CreateAIQuota :one
insert into ai_quotas (service_id, tenant_id, metric, limit_quantity, period, enforcement)
values ($1, $2, $3, $4, $5, $6)
returning id, service_id, tenant_id, metric, limit_quantity, period, enforcement, created_at
`

type CreateAIQuotaParams struct {
	ServiceID     pgtype.UUID `json:"service_id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
	Metric        string      `json:"metric"`
	LimitQuantity float64     `json:"limit_quantity"`
	Period        string      `json:"period"`
	Enforcement   string      `json:"enforcement"`
}

func (q *Queries) CreateAIQuota(ctx context.Context, arg CreateAIQuotaParams) (AiQuota, error) {
	row := q.db.QueryRow(ctx, createAIQuota,
		arg.ServiceID,
		arg.TenantID,
		arg.Metric,
		arg.LimitQuantity,
		arg.Period,
		arg.Enforcement,
	)
	var i AiQuota
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.TenantID,
		&i.Metric,
		&i.LimitQuantity,
		&i.Period,
		&i.Enforcement,
		&i.CreatedAt,
	)
	return i, err
}

const createAIService = `-- name: CreateAIService :one
insert into ai_services (provider_id, name, slug, category, description, request_schema, default_expiration_days, requires_approval)
values ($1, $2, $3, $4, $5, $6, $7, $8)
returning id, provider_id, name, slug, category, description, request_schema, default_expiration_days, requires_approval, status, created_at, updated_at
`

type CreateAIServiceParams struct {
	ProviderID            uuid.UUID `json:"provider_id"`
	Name                  string    `json:"name"`
	Slug                  string    `json:"slug"`
	Category              string    `json:"category"`
	Description           string    `json:"description"`
	RequestSchema         []byte    `json:"request_schema"`
	DefaultExpirationDays int32     `json:"default_expiration_days"`
	RequiresApproval      bool      `json:"requires_approval"`
}

func (q *Queries) CreateAIService(ctx context.Context, arg CreateAIServiceParams) (AiService, error) {
	row := q.db.QueryRow(ctx, createAIService,
		arg.ProviderID,
		arg.Name,
		arg.Slug,
		arg.Category,
		arg.Description,
		arg.RequestSchema,
		arg.DefaultExpirationDays,
		arg.RequiresApproval,
	)
	var i AiService
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Name,
		&i.Slug,
		&i.Category,
		&i.Description,
		&i.RequestSchema,
		&i.DefaultExpirationDays,
		&i.RequiresApproval,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAIServiceInstance = `-- name: CreateAIServiceInstance :one
insert into ai_service_instances (
    service_id, request_id, provider_access_id, owner, tenant_id, workspace,
    status, spec, observed, provisioned_at, expires_at
)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
returning id, service_id, request_id, provider_access_id, owner, tenant_id, workspace, status, spec, observed, provisioned_at, expires_at, revoked_at, created_at, updated_at
`

type CreateAIServiceInstanceParams struct {
	ServiceID        uuid.UUID          `json:"service_id"`
	RequestID        pgtype.UUID        `json:"request_id"`
	ProviderAccessID string             `json:"provider_access_id"`
	Owner            string             `json:"owner"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	Workspace        string             `json:"workspace"`
	Status           string             `json:"status"`
	Spec             []byte             `json:"spec"`
	Observed         []byte             `json:"observed"`
	ProvisionedAt    pgtype.Timestamptz `json:"provisioned_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAIServiceInstance(ctx context.Context, arg CreateAIServiceInstanceParams) (AiServiceInstance, error) {
	row := q.db.QueryRow(ctx, createAIServiceInstance,
		arg.ServiceID,
		arg.RequestID,
		arg.ProviderAccessID,
		arg.Owner,
		arg.TenantID,
		arg.Workspace,
		arg.Status,
		arg.Spec,
		arg.Observed,
		arg.ProvisionedAt,
		arg.ExpiresAt,
	)
	var i AiServiceInstance
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.RequestID,
		&i.ProviderAccessID,
		&i.Owner,
		&i.TenantID,
		&i.Workspace,
		&i.Status,
		&i.Spec,
		&i.Observed,
		&i.ProvisionedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAIUsageRecord = `-- name: CreateAIUsageRecord :one
insert into ai_usage_records (
    instance_id, provider_id, period_start, period_end, metric, quantity, unit, cost_usd, raw
)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
returning id, instance_id, provider_id, period_start, period_end, metric, quantity, unit, cost_usd, raw, created_at
`

type CreateAIUsageRecordParams struct {
	InstanceID  pgtype.UUID `json:"instance_id"`
	ProviderID  uuid.UUID   `json:"provider_id"`
	PeriodStart time.Time   `json:"period_start"`
	PeriodEnd   time.Time   `json:"period_end"`
	Metric      string      `json:"metric"`
	Quantity    float64     `json:"quantity"`
	Unit        string      `json:"unit"`
	CostUsd     float64     `json:"cost_usd"`
	Raw         []byte      `json:"raw"`
}

func (q *Queries) CreateAIUsageRecord(ctx context.Context, arg CreateAIUsageRecordParams) (AiUsageRecord, error) {
	row := q.db.QueryRow(ctx, createAIUsageRecord,
		arg.InstanceID,
		arg.ProviderID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Metric,
		arg.Quantity,
		arg.Unit,
		arg.CostUsd,
		arg.Raw,
	)
	var i AiUsageRecord
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.ProviderID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Metric,
		&i.Quantity,
		&i.Unit,
		&i.CostUsd,
		&i.Raw,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAIAccessPolicy = `-- name: DeleteAIAccessPolicy :exec
delete from ai_access_policies where id = $1
`

func (q *Queries) DeleteAIAccessPolicy(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAIAccessPolicy, id)
	return err
}

const deleteAIBudget = `-- name: DeleteAIBudget :exec
delete from ai_budgets where id = $1
`

func (q *Queries) DeleteAIBudget(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAIBudget, id)
	return err
}

const deleteAIProvider = `-- name: DeleteAIProvider :exec
delete from ai_providers where id = $1
`

func (q *Queries) DeleteAIProvider(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAIProvider, id)
	return err
}

const deleteAIQuota = `-- name: DeleteAIQuota :exec
delete from ai_quotas where id = $1
`

func (q *Queries) DeleteAIQuota(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAIQuota, id)
	return err
}

const deleteAIServiceInstancesByProvider = `-- name: DeleteAIServiceInstancesByProvider :exec
delete from ai_service_instances
where service_id in (select id from ai_services where provider_id = $1)
`

func (q *Queries) DeleteAIServiceInstancesByProvider(ctx context.Context, providerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAIServiceInstancesByProvider, providerID)
	return err
}

const expireAIServiceInstances = `-- name: ExpireAIServiceInstances :many
update ai_service_instances
set status = 'expired', updated_at = now()
where status in ('active', 'suspended')
  and expires_at is not null
  and expires_at < now()
returning id, service_id, request_id, provider_access_id, owner, tenant_id, workspace, status, spec, observed, provisioned_at, expires_at, revoked_at, created_at, updated_at
`

func (q *Queries) ExpireAIServiceInstances(ctx context.Context) ([]AiServiceInstance, error) {
	rows, err := q.db.Query(ctx, expireAIServiceInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiServiceInstance{}
	for rows.Next() {
		var i AiServiceInstance
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.RequestID,
			&i.ProviderAccessID,
			&i.Owner,
			&i.TenantID,
			&i.Workspace,
			&i.Status,
			&i.Spec,
			&i.Observed,
			&i.ProvisionedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAIUsageRecordByImportKey = `-- name: FindAIUsageRecordByImportKey :one
select id, instance_id, provider_id, period_start, period_end, metric, quantity, unit, cost_usd, raw, created_at
from ai_usage_records
where provider_id = $1
  and period_start = $2
  and period_end = $3
  and metric = $4
  and raw->>'import_key' = $5::text
limit 1
`

type FindAIUsageRecordByImportKeyParams struct {
	ProviderID  uuid.UUID `json:"provider_id"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
	Metric      string    `json:"metric"`
	ImportKey   string    `json:"import_key"`
}

func (q *Queries) FindAIUsageRecordByImportKey(ctx context.Context, arg FindAIUsageRecordByImportKeyParams) (AiUsageRecord, error) {
	row := q.db.QueryRow(ctx, findAIUsageRecordByImportKey,
		arg.ProviderID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Metric,
		arg.ImportKey,
	)
	var i AiUsageRecord
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.ProviderID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Metric,
		&i.Quantity,
		&i.Unit,
		&i.CostUsd,
		&i.Raw,
		&i.CreatedAt,
	)
	return i, err
}

const getAIBudget = `-- name: GetAIBudget :one
select id, tenant_id, scope, scope_ref, limit_usd, period, soft_threshold_pct, hard_threshold_pct, created_at, updated_at from ai_budgets where id = $1
`

func (q *Queries) GetAIBudget(ctx context.Context, id uuid.UUID) (AiBudget, error) {
	row := q.db.QueryRow(ctx, getAIBudget, id)
	var i AiBudget
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Scope,
		&i.ScopeRef,
		&i.LimitUsd,
		&i.Period,
		&i.SoftThresholdPct,
		&i.HardThresholdPct,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAIProvider = `-- name: GetAIProvider :one
select id, name, type, config, status, tenant_id, created_at, updated_at from ai_providers where id = $1
`

func (q *Queries) GetAIProvider(ctx context.Context, id uuid.UUID) (AiProvider, error) {
	row := q.db.QueryRow(ctx, getAIProvider, id)
	var i AiProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Status,
		&i.TenantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAIProviderByName = `-- name: GetAIProviderByName :one
select id, name, type, config, status, tenant_id, created_at, updated_at from ai_providers where name = $1
`

func (q *Queries) GetAIProviderByName(ctx context.Context, name string) (AiProvider, error) {
	row := q.db.QueryRow(ctx, getAIProviderByName, name)
	var i AiProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Status,
		&i.TenantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAIProviderCredentialByProvider = `-- name: GetAIProviderCredentialByProvider :one
select id, provider_id, secret_ref, scopes, rotation_due_at, last_validated_at, last_validation_status, created_at from ai_provider_credentials
where provider_id = $1
order by created_at desc
limit 1
`

func (q *Queries) GetAIProviderCredentialByProvider(ctx context.Context, providerID uuid.UUID) (AiProviderCredential, error) {
	row := q.db.QueryRow(ctx, getAIProviderCredentialByProvider, providerID)
	var i AiProviderCredential
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.SecretRef,
		&i.Scopes,
		&i.RotationDueAt,
		&i.LastValidatedAt,
		&i.LastValidationStatus,
		&i.CreatedAt,
	)
	return i, err
}

const getAIService = `-- name: GetAIService :one
select
    s.id, s.provider_id, s.name, s.slug, s.category, s.description, s.request_schema, s.default_expiration_days, s.requires_approval, s.status, s.created_at, s.updated_at,
    p.name as provider_name,
    p.type as provider_type
from ai_services s
join ai_providers p on p.id = s.provider_id
where s.id = $1
`

type GetAIServiceRow struct {
	ID                    uuid.UUID `json:"id"`
	ProviderID            uuid.UUID `json:"provider_id"`
	Name                  string    `json:"name"`
	Slug                  string    `json:"slug"`
	Category              string    `json:"category"`
	Description           string    `json:"description"`
	RequestSchema         []byte    `json:"request_schema"`
	DefaultExpirationDays int32     `json:"default_expiration_days"`
	RequiresApproval      bool      `json:"requires_approval"`
	Status                string    `json:"status"`
	CreatedAt             time.Time `json:"created_at"`
	UpdatedAt             time.Time `json:"updated_at"`
	ProviderName          string    `json:"provider_name"`
	ProviderType          string    `json:"provider_type"`
}

func (q *Queries) GetAIService(ctx context.Context, id uuid.UUID) (GetAIServiceRow, error) {
	row := q.db.QueryRow(ctx, getAIService, id)
	var i GetAIServiceRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Name,
		&i.Slug,
		&i.Category,
		&i.Description,
		&i.RequestSchema,
		&i.DefaultExpirationDays,
		&i.RequiresApproval,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderName,
		&i.ProviderType,
	)
	return i, err
}

const getAIServiceBySlug = `-- name: GetAIServiceBySlug :one
select
    s.id, s.provider_id, s.name, s.slug, s.category, s.description, s.request_schema, s.default_expiration_days, s.requires_approval, s.status, s.created_at, s.updated_at,
    p.name as provider_name,
    p.type as provider_type
from ai_services s
join ai_providers p on p.id = s.provider_id
where s.slug = $1
`

type GetAIServiceBySlugRow struct {
	ID                    uuid.UUID `json:"id"`
	ProviderID            uuid.UUID `json:"provider_id"`
	Name                  string    `json:"name"`
	Slug                  string    `json:"slug"`
	Category              string    `json:"category"`
	Description           string    `json:"description"`
	RequestSchema         []byte    `json:"request_schema"`
	DefaultExpirationDays int32     `json:"default_expiration_days"`
	RequiresApproval      bool      `json:"requires_approval"`
	Status                string    `json:"status"`
	CreatedAt             time.Time `json:"created_at"`
	UpdatedAt             time.Time `json:"updated_at"`
	ProviderName          string    `json:"provider_name"`
	ProviderType          string    `json:"provider_type"`
}

func (q *Queries) GetAIServiceBySlug(ctx context.Context, slug string) (GetAIServiceBySlugRow, error) {
	row := q.db.QueryRow(ctx, getAIServiceBySlug, slug)
	var i GetAIServiceBySlugRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Name,
		&i.Slug,
		&i.Category,
		&i.Description,
		&i.RequestSchema,
		&i.DefaultExpirationDays,
		&i.RequiresApproval,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProviderName,
		&i.ProviderType,
	)
	return i, err
}

const getAIServiceInstance = `-- name: GetAIServiceInstance :one
select id, service_id, request_id, provider_access_id, owner, tenant_id, workspace, status, spec, observed, provisioned_at, expires_at, revoked_at, created_at, updated_at from ai_service_instances where id = $1
`

func (q *Queries) GetAIServiceInstance(ctx context.Context, id uuid.UUID) (AiServiceInstance, error) {
	row := q.db.QueryRow(ctx, getAIServiceInstance, id)
	var i AiServiceInstance
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.RequestID,
		&i.ProviderAccessID,
		&i.Owner,
		&i.TenantID,
		&i.Workspace,
		&i.Status,
		&i.Spec,
		&i.Observed,
		&i.ProvisionedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAIAccessPolicies = `-- name: ListAIAccessPolicies :many
select id, name, tenant_id, rules, status, created_at, updated_at from ai_access_policies order by created_at desc
`

func (q *Queries) ListAIAccessPolicies(ctx context.Context) ([]AiAccessPolicy, error) {
	rows, err := q.db.Query(ctx, listAIAccessPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiAccessPolicy{}
	for rows.Next() {
		var i AiAccessPolicy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TenantID,
			&i.Rules,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIAuditEvents = `-- name: ListAIAuditEvents :many
select id, actor, tenant_id, subject_type, subject_id, action, message, fields, created_at from ai_audit_events order by created_at desc limit $1
`

func (q *Queries) ListAIAuditEvents(ctx context.Context, limit int32) ([]AiAuditEvent, error) {
	rows, err := q.db.Query(ctx, listAIAuditEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiAuditEvent{}
	for rows.Next() {
		var i AiAuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.Actor,
			&i.TenantID,
			&i.SubjectType,
			&i.SubjectID,
			&i.Action,
			&i.Message,
			&i.Fields,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIBudgets = `-- name: ListAIBudgets :many
select id, tenant_id, scope, scope_ref, limit_usd, period, soft_threshold_pct, hard_threshold_pct, created_at, updated_at from ai_budgets order by created_at desc
`

func (q *Queries) ListAIBudgets(ctx context.Context) ([]AiBudget, error) {
	rows, err := q.db.Query(ctx, listAIBudgets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiBudget{}
	for rows.Next() {
		var i AiBudget
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Scope,
			&i.ScopeRef,
			&i.LimitUsd,
			&i.Period,
			&i.SoftThresholdPct,
			&i.HardThresholdPct,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIExpiringInstances = `-- name: ListAIExpiringInstances :many
select
    i.id, i.service_id, i.request_id, i.provider_access_id, i.owner, i.tenant_id, i.workspace, i.status, i.spec, i.observed, i.provisioned_at, i.expires_at, i.revoked_at, i.created_at, i.updated_at,
    s.name as service_name,
    s.slug as service_slug,
    p.name as provider_name,
    p.type as provider_type
from ai_service_instances i
join ai_services s on s.id = i.service_id
join ai_providers p on p.id = s.provider_id
where i.status in ('active', 'suspended')
  and i.expires_at is not null
  and i.expires_at >= now()
  and i.expires_at <= now() + ($1::int * interval '1 day')
order by i.expires_at asc
`

type ListAIExpiringInstancesRow struct {
	ID               uuid.UUID          `json:"id"`
	ServiceID        uuid.UUID          `json:"service_id"`
	RequestID        pgtype.UUID        `json:"request_id"`
	ProviderAccessID string             `json:"provider_access_id"`
	Owner            string             `json:"owner"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	Workspace        string             `json:"workspace"`
	Status           string             `json:"status"`
	Spec             []byte             `json:"spec"`
	Observed         []byte             `json:"observed"`
	ProvisionedAt    pgtype.Timestamptz `json:"provisioned_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	ServiceName      string             `json:"service_name"`
	ServiceSlug      string             `json:"service_slug"`
	ProviderName     string             `json:"provider_name"`
	ProviderType     string             `json:"provider_type"`
}

func (q *Queries) ListAIExpiringInstances(ctx context.Context, dollar_1 int32) ([]ListAIExpiringInstancesRow, error) {
	rows, err := q.db.Query(ctx, listAIExpiringInstances, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAIExpiringInstancesRow{}
	for rows.Next() {
		var i ListAIExpiringInstancesRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.RequestID,
			&i.ProviderAccessID,
			&i.Owner,
			&i.TenantID,
			&i.Workspace,
			&i.Status,
			&i.Spec,
			&i.Observed,
			&i.ProvisionedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServiceName,
			&i.ServiceSlug,
			&i.ProviderName,
			&i.ProviderType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIModelCatalog = `-- name: ListAIModelCatalog :many
select
    m.id, m.provider_id, m.model, m.display_name, m.modality, m.status, m.metadata, m.created_at, m.updated_at,
    p.name as provider_name,
    p.type as provider_type
from ai_model_catalog m
join ai_providers p on p.id = m.provider_id
order by p.name, m.model
`

type ListAIModelCatalogRow struct {
	ID           uuid.UUID `json:"id"`
	ProviderID   uuid.UUID `json:"provider_id"`
	Model        string    `json:"model"`
	DisplayName  string    `json:"display_name"`
	Modality     string    `json:"modality"`
	Status       string    `json:"status"`
	Metadata     []byte    `json:"metadata"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	ProviderName string    `json:"provider_name"`
	ProviderType string    `json:"provider_type"`
}

func (q *Queries) ListAIModelCatalog(ctx context.Context) ([]ListAIModelCatalogRow, error) {
	rows, err := q.db.Query(ctx, listAIModelCatalog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAIModelCatalogRow{}
	for rows.Next() {
		var i ListAIModelCatalogRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Model,
			&i.DisplayName,
			&i.Modality,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProviderName,
			&i.ProviderType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIProviderCredentials = `-- name: ListAIProviderCredentials :many
select id, provider_id, secret_ref, scopes, rotation_due_at, last_validated_at, last_validation_status, created_at from ai_provider_credentials order by created_at desc
`

func (q *Queries) ListAIProviderCredentials(ctx context.Context) ([]AiProviderCredential, error) {
	rows, err := q.db.Query(ctx, listAIProviderCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiProviderCredential{}
	for rows.Next() {
		var i AiProviderCredential
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.SecretRef,
			&i.Scopes,
			&i.RotationDueAt,
			&i.LastValidatedAt,
			&i.LastValidationStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIProviders = `-- name: ListAIProviders :many
select id, name, type, config, status, tenant_id, created_at, updated_at from ai_providers order by created_at desc
`

func (q *Queries) ListAIProviders(ctx context.Context) ([]AiProvider, error) {
	rows, err := q.db.Query(ctx, listAIProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiProvider{}
	for rows.Next() {
		var i AiProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.Status,
			&i.TenantID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIQuotas = `-- name: ListAIQuotas :many
select id, service_id, tenant_id, metric, limit_quantity, period, enforcement, created_at from ai_quotas order by created_at desc
`

func (q *Queries) ListAIQuotas(ctx context.Context) ([]AiQuota, error) {
	rows, err := q.db.Query(ctx, listAIQuotas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiQuota{}
	for rows.Next() {
		var i AiQuota
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.TenantID,
			&i.Metric,
			&i.LimitQuantity,
			&i.Period,
			&i.Enforcement,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIServiceInstances = `-- name: ListAIServiceInstances :many
select
    i.id, i.service_id, i.request_id, i.provider_access_id, i.owner, i.tenant_id, i.workspace, i.status, i.spec, i.observed, i.provisioned_at, i.expires_at, i.revoked_at, i.created_at, i.updated_at,
    s.name as service_name,
    s.slug as service_slug,
    p.name as provider_name,
    p.type as provider_type
from ai_service_instances i
join ai_services s on s.id = i.service_id
join ai_providers p on p.id = s.provider_id
order by i.created_at desc
`

type ListAIServiceInstancesRow struct {
	ID               uuid.UUID          `json:"id"`
	ServiceID        uuid.UUID          `json:"service_id"`
	RequestID        pgtype.UUID        `json:"request_id"`
	ProviderAccessID string             `json:"provider_access_id"`
	Owner            string             `json:"owner"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	Workspace        string             `json:"workspace"`
	Status           string             `json:"status"`
	Spec             []byte             `json:"spec"`
	Observed         []byte             `json:"observed"`
	ProvisionedAt    pgtype.Timestamptz `json:"provisioned_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	ServiceName      string             `json:"service_name"`
	ServiceSlug      string             `json:"service_slug"`
	ProviderName     string             `json:"provider_name"`
	ProviderType     string             `json:"provider_type"`
}

func (q *Queries) ListAIServiceInstances(ctx context.Context) ([]ListAIServiceInstancesRow, error) {
	rows, err := q.db.Query(ctx, listAIServiceInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAIServiceInstancesRow{}
	for rows.Next() {
		var i ListAIServiceInstancesRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.RequestID,
			&i.ProviderAccessID,
			&i.Owner,
			&i.TenantID,
			&i.Workspace,
			&i.Status,
			&i.Spec,
			&i.Observed,
			&i.ProvisionedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServiceName,
			&i.ServiceSlug,
			&i.ProviderName,
			&i.ProviderType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIServices = `-- name: ListAIServices :many
select
    s.id, s.provider_id, s.name, s.slug, s.category, s.description, s.request_schema, s.default_expiration_days, s.requires_approval, s.status, s.created_at, s.updated_at,
    p.name as provider_name,
    p.type as provider_type
from ai_services s
join ai_providers p on p.id = s.provider_id
order by s.created_at desc
`

type ListAIServicesRow struct {
	ID                    uuid.UUID `json:"id"`
	ProviderID            uuid.UUID `json:"provider_id"`
	Name                  string    `json:"name"`
	Slug                  string    `json:"slug"`
	Category              string    `json:"category"`
	Description           string    `json:"description"`
	RequestSchema         []byte    `json:"request_schema"`
	DefaultExpirationDays int32     `json:"default_expiration_days"`
	RequiresApproval      bool      `json:"requires_approval"`
	Status                string    `json:"status"`
	CreatedAt             time.Time `json:"created_at"`
	UpdatedAt             time.Time `json:"updated_at"`
	ProviderName          string    `json:"provider_name"`
	ProviderType          string    `json:"provider_type"`
}

func (q *Queries) ListAIServices(ctx context.Context) ([]ListAIServicesRow, error) {
	rows, err := q.db.Query(ctx, listAIServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAIServicesRow{}
	for rows.Next() {
		var i ListAIServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Name,
			&i.Slug,
			&i.Category,
			&i.Description,
			&i.RequestSchema,
			&i.DefaultExpirationDays,
			&i.RequiresApproval,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProviderName,
			&i.ProviderType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAIUsageRecords = `-- name: ListAIUsageRecords :many
select
    u.id, u.instance_id, u.provider_id, u.period_start, u.period_end, u.metric, u.quantity, u.unit, u.cost_usd, u.raw, u.created_at,
    p.name as provider_name,
    i.owner as owner,
    i.workspace as workspace,
    i.tenant_id as tenant_id
from ai_usage_records u
join ai_providers p on p.id = u.provider_id
left join ai_service_instances i on i.id = u.instance_id
order by u.period_start desc, u.created_at desc
`

type ListAIUsageRecordsRow struct {
	ID           uuid.UUID   `json:"id"`
	InstanceID   pgtype.UUID `json:"instance_id"`
	ProviderID   uuid.UUID   `json:"provider_id"`
	PeriodStart  time.Time   `json:"period_start"`
	PeriodEnd    time.Time   `json:"period_end"`
	Metric       string      `json:"metric"`
	Quantity     float64     `json:"quantity"`
	Unit         string      `json:"unit"`
	CostUsd      float64     `json:"cost_usd"`
	Raw          []byte      `json:"raw"`
	CreatedAt    time.Time   `json:"created_at"`
	ProviderName string      `json:"provider_name"`
	Owner        *string     `json:"owner"`
	Workspace    *string     `json:"workspace"`
	TenantID     pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) ListAIUsageRecords(ctx context.Context) ([]ListAIUsageRecordsRow, error) {
	rows, err := q.db.Query(ctx, listAIUsageRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAIUsageRecordsRow{}
	for rows.Next() {
		var i ListAIUsageRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.ProviderID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Metric,
			&i.Quantity,
			&i.Unit,
			&i.CostUsd,
			&i.Raw,
			&i.CreatedAt,
			&i.ProviderName,
			&i.Owner,
			&i.Workspace,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAIServiceInstance = `-- name: RevokeAIServiceInstance :one
update ai_service_instances
set status = 'revoked', revoked_at = now(), updated_at = now()
where id = $1 and status in ('active', 'suspended')
returning id, service_id, request_id, provider_access_id, owner, tenant_id, workspace, status, spec, observed, provisioned_at, expires_at, revoked_at, created_at, updated_at
`

func (q *Queries) RevokeAIServiceInstance(ctx context.Context, id uuid.UUID) (AiServiceInstance, error) {
	row := q.db.QueryRow(ctx, revokeAIServiceInstance, id)
	var i AiServiceInstance
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.RequestID,
		&i.ProviderAccessID,
		&i.Owner,
		&i.TenantID,
		&i.Workspace,
		&i.Status,
		&i.Spec,
		&i.Observed,
		&i.ProvisionedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAIProvider = `-- name: UpdateAIProvider :one
update ai_providers
set name = $2, type = $3, config = $4, status = $5, updated_at = now()
where id = $1
returning id, name, type, config, status, tenant_id, created_at, updated_at
`

type UpdateAIProviderParams struct {
	ID     uuid.UUID `json:"id"`
	Name   string    `json:"name"`
	Type   string    `json:"type"`
	Config []byte    `json:"config"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateAIProvider(ctx context.Context, arg UpdateAIProviderParams) (AiProvider, error) {
	row := q.db.QueryRow(ctx, updateAIProvider,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.Status,
	)
	var i AiProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Status,
		&i.TenantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAIServiceInstanceStatus = `-- name: UpdateAIServiceInstanceStatus :one
update ai_service_instances
set status = $2, observed = $3, updated_at = now()
where id = $1
returning id, service_id, request_id, provider_access_id, owner, tenant_id, workspace, status, spec, observed, provisioned_at, expires_at, revoked_at, created_at, updated_at
`

type UpdateAIServiceInstanceStatusParams struct {
	ID       uuid.UUID `json:"id"`
	Status   string    `json:"status"`
	Observed []byte    `json:"observed"`
}

func (q *Queries) UpdateAIServiceInstanceStatus(ctx context.Context, arg UpdateAIServiceInstanceStatusParams) (AiServiceInstance, error) {
	row := q.db.QueryRow(ctx, updateAIServiceInstanceStatus, arg.ID, arg.Status, arg.Observed)
	var i AiServiceInstance
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.RequestID,
		&i.ProviderAccessID,
		&i.Owner,
		&i.TenantID,
		&i.Workspace,
		&i.Status,
		&i.Spec,
		&i.Observed,
		&i.ProvisionedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAIModelCatalog = `-- name: UpsertAIModelCatalog :one
insert into ai_model_catalog (provider_id, model, display_name, modality, status, metadata)
values ($1, $2, $3, $4, $5, $6)
on conflict (provider_id, model) do update
set display_name = excluded.display_name,
    modality = excluded.modality,
    status = excluded.status,
    metadata = excluded.metadata,
    updated_at = now()
returning id, provider_id, model, display_name, modality, status, metadata, created_at, updated_at
`

type UpsertAIModelCatalogParams struct {
	ProviderID  uuid.UUID `json:"provider_id"`
	Model       string    `json:"model"`
	DisplayName string    `json:"display_name"`
	Modality    string    `json:"modality"`
	Status      string    `json:"status"`
	Metadata    []byte    `json:"metadata"`
}

func (q *Queries) UpsertAIModelCatalog(ctx context.Context, arg UpsertAIModelCatalogParams) (AiModelCatalog, error) {
	row := q.db.QueryRow(ctx, upsertAIModelCatalog,
		arg.ProviderID,
		arg.Model,
		arg.DisplayName,
		arg.Modality,
		arg.Status,
		arg.Metadata,
	)
	var i AiModelCatalog
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Model,
		&i.DisplayName,
		&i.Modality,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
