// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backups.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBackup = `-- name: CreateBackup :one
insert into backups (resource_kind, resource_name, environment, provider, tofu_workspace, tenant_id)
values ($1, $2, $3, $4, $5, $6)
returning id, resource_kind, resource_name, environment, provider, snapshot_id, tofu_workspace, status, tenant_id, created_at, updated_at
`

type CreateBackupParams struct {
	ResourceKind  string      `json:"resource_kind"`
	ResourceName  string      `json:"resource_name"`
	Environment   string      `json:"environment"`
	Provider      string      `json:"provider"`
	TofuWorkspace string      `json:"tofu_workspace"`
	TenantID      pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) CreateBackup(ctx context.Context, arg CreateBackupParams) (Backup, error) {
	row := q.db.QueryRow(ctx, createBackup,
		arg.ResourceKind,
		arg.ResourceName,
		arg.Environment,
		arg.Provider,
		arg.TofuWorkspace,
		arg.TenantID,
	)
	var i Backup
	err := row.Scan(
		&i.ID,
		&i.ResourceKind,
		&i.ResourceName,
		&i.Environment,
		&i.Provider,
		&i.SnapshotID,
		&i.TofuWorkspace,
		&i.Status,
		&i.TenantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBackup = `-- name: GetBackup :one
select id, resource_kind, resource_name, environment, provider, snapshot_id, tofu_workspace, status, tenant_id, created_at, updated_at from backups where id = $1
`

func (q *Queries) GetBackup(ctx context.Context, id uuid.UUID) (Backup, error) {
	row := q.db.QueryRow(ctx, getBackup, id)
	var i Backup
	err := row.Scan(
		&i.ID,
		&i.ResourceKind,
		&i.ResourceName,
		&i.Environment,
		&i.Provider,
		&i.SnapshotID,
		&i.TofuWorkspace,
		&i.Status,
		&i.TenantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBackups = `-- name: ListBackups :many
select id, resource_kind, resource_name, environment, provider, snapshot_id, tofu_workspace, status, tenant_id, created_at, updated_at from backups order by created_at desc
`

func (q *Queries) ListBackups(ctx context.Context) ([]Backup, error) {
	rows, err := q.db.Query(ctx, listBackups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Backup{}
	for rows.Next() {
		var i Backup
		if err := rows.Scan(
			&i.ID,
			&i.ResourceKind,
			&i.ResourceName,
			&i.Environment,
			&i.Provider,
			&i.SnapshotID,
			&i.TofuWorkspace,
			&i.Status,
			&i.TenantID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBackupResult = `-- name: SetBackupResult :one
update backups
set snapshot_id = $2, status = $3, updated_at = now()
where id = $1
returning id, resource_kind, resource_name, environment, provider, snapshot_id, tofu_workspace, status, tenant_id, created_at, updated_at
`

type SetBackupResultParams struct {
	ID         uuid.UUID `json:"id"`
	SnapshotID string    `json:"snapshot_id"`
	Status     string    `json:"status"`
}

func (q *Queries) SetBackupResult(ctx context.Context, arg SetBackupResultParams) (Backup, error) {
	row := q.db.QueryRow(ctx, setBackupResult, arg.ID, arg.SnapshotID, arg.Status)
	var i Backup
	err := row.Scan(
		&i.ID,
		&i.ResourceKind,
		&i.ResourceName,
		&i.Environment,
		&i.Provider,
		&i.SnapshotID,
		&i.TofuWorkspace,
		&i.Status,
		&i.TenantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
