// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clusters.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCluster = `-- name: CreateCluster :one
insert into clusters (name, environment, provider_id, desired_spec, tofu_workspace, tenant_id)
values ($1, $2, $3, $4, $5, $6)
returning id, name, environment, provider_id, status, desired_spec, observed_state, tofu_workspace, kubeconfig_ref, created_at, updated_at, tenant_id
`

type CreateClusterParams struct {
	Name          string      `json:"name"`
	Environment   string      `json:"environment"`
	ProviderID    uuid.UUID   `json:"provider_id"`
	DesiredSpec   []byte      `json:"desired_spec"`
	TofuWorkspace string      `json:"tofu_workspace"`
	TenantID      pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) CreateCluster(ctx context.Context, arg CreateClusterParams) (Cluster, error) {
	row := q.db.QueryRow(ctx, createCluster,
		arg.Name,
		arg.Environment,
		arg.ProviderID,
		arg.DesiredSpec,
		arg.TofuWorkspace,
		arg.TenantID,
	)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Environment,
		&i.ProviderID,
		&i.Status,
		&i.DesiredSpec,
		&i.ObservedState,
		&i.TofuWorkspace,
		&i.KubeconfigRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const deleteCluster = `-- name: DeleteCluster :exec
delete from clusters where id = $1
`

func (q *Queries) DeleteCluster(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCluster, id)
	return err
}

const getCluster = `-- name: GetCluster :one
select id, name, environment, provider_id, status, desired_spec, observed_state, tofu_workspace, kubeconfig_ref, created_at, updated_at, tenant_id from clusters where id = $1
`

func (q *Queries) GetCluster(ctx context.Context, id uuid.UUID) (Cluster, error) {
	row := q.db.QueryRow(ctx, getCluster, id)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Environment,
		&i.ProviderID,
		&i.Status,
		&i.DesiredSpec,
		&i.ObservedState,
		&i.TofuWorkspace,
		&i.KubeconfigRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const getClusterByName = `-- name: GetClusterByName :one
select id, name, environment, provider_id, status, desired_spec, observed_state, tofu_workspace, kubeconfig_ref, created_at, updated_at, tenant_id from clusters where name = $1 and environment = $2
`

type GetClusterByNameParams struct {
	Name        string `json:"name"`
	Environment string `json:"environment"`
}

func (q *Queries) GetClusterByName(ctx context.Context, arg GetClusterByNameParams) (Cluster, error) {
	row := q.db.QueryRow(ctx, getClusterByName, arg.Name, arg.Environment)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Environment,
		&i.ProviderID,
		&i.Status,
		&i.DesiredSpec,
		&i.ObservedState,
		&i.TofuWorkspace,
		&i.KubeconfigRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const listClusters = `-- name: ListClusters :many
select id, name, environment, provider_id, status, desired_spec, observed_state, tofu_workspace, kubeconfig_ref, created_at, updated_at, tenant_id from clusters order by created_at desc
`

func (q *Queries) ListClusters(ctx context.Context) ([]Cluster, error) {
	rows, err := q.db.Query(ctx, listClusters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cluster{}
	for rows.Next() {
		var i Cluster
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Environment,
			&i.ProviderID,
			&i.Status,
			&i.DesiredSpec,
			&i.ObservedState,
			&i.TofuWorkspace,
			&i.KubeconfigRef,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClustersByProvider = `-- name: ListClustersByProvider :many
select id, name, environment, provider_id, status, desired_spec, observed_state, tofu_workspace, kubeconfig_ref, created_at, updated_at, tenant_id from clusters where provider_id = $1 order by created_at desc
`

func (q *Queries) ListClustersByProvider(ctx context.Context, providerID uuid.UUID) ([]Cluster, error) {
	rows, err := q.db.Query(ctx, listClustersByProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cluster{}
	for rows.Next() {
		var i Cluster
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Environment,
			&i.ProviderID,
			&i.Status,
			&i.DesiredSpec,
			&i.ObservedState,
			&i.TofuWorkspace,
			&i.KubeconfigRef,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClusterSpec = `-- name: UpdateClusterSpec :one
update clusters
set desired_spec = $2, updated_at = now()
where id = $1
returning id, name, environment, provider_id, status, desired_spec, observed_state, tofu_workspace, kubeconfig_ref, created_at, updated_at, tenant_id
`

type UpdateClusterSpecParams struct {
	ID          uuid.UUID `json:"id"`
	DesiredSpec []byte    `json:"desired_spec"`
}

func (q *Queries) UpdateClusterSpec(ctx context.Context, arg UpdateClusterSpecParams) (Cluster, error) {
	row := q.db.QueryRow(ctx, updateClusterSpec, arg.ID, arg.DesiredSpec)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Environment,
		&i.ProviderID,
		&i.Status,
		&i.DesiredSpec,
		&i.ObservedState,
		&i.TofuWorkspace,
		&i.KubeconfigRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const updateClusterState = `-- name: UpdateClusterState :one
update clusters
set observed_state = $2, kubeconfig_ref = $3, updated_at = now()
where id = $1
returning id, name, environment, provider_id, status, desired_spec, observed_state, tofu_workspace, kubeconfig_ref, created_at, updated_at, tenant_id
`

type UpdateClusterStateParams struct {
	ID            uuid.UUID `json:"id"`
	ObservedState []byte    `json:"observed_state"`
	KubeconfigRef *string   `json:"kubeconfig_ref"`
}

func (q *Queries) UpdateClusterState(ctx context.Context, arg UpdateClusterStateParams) (Cluster, error) {
	row := q.db.QueryRow(ctx, updateClusterState, arg.ID, arg.ObservedState, arg.KubeconfigRef)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Environment,
		&i.ProviderID,
		&i.Status,
		&i.DesiredSpec,
		&i.ObservedState,
		&i.TofuWorkspace,
		&i.KubeconfigRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const updateClusterStatus = `-- name: UpdateClusterStatus :one
update clusters
set status = $2, updated_at = now()
where id = $1
returning id, name, environment, provider_id, status, desired_spec, observed_state, tofu_workspace, kubeconfig_ref, created_at, updated_at, tenant_id
`

type UpdateClusterStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateClusterStatus(ctx context.Context, arg UpdateClusterStatusParams) (Cluster, error) {
	row := q.db.QueryRow(ctx, updateClusterStatus, arg.ID, arg.Status)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Environment,
		&i.ProviderID,
		&i.Status,
		&i.DesiredSpec,
		&i.ObservedState,
		&i.TofuWorkspace,
		&i.KubeconfigRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}
