// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environments.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEnvironment = `-- name: CreateEnvironment :one
insert into environments (name, environment, blueprint, spec, tenant_id)
values ($1, $2, $3, $4, $5)
returning id, name, environment, blueprint, status, spec, created_at, updated_at, tenant_id
`

type CreateEnvironmentParams struct {
	Name        string      `json:"name"`
	Environment string      `json:"environment"`
	Blueprint   string      `json:"blueprint"`
	Spec        []byte      `json:"spec"`
	TenantID    pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment,
		arg.Name,
		arg.Environment,
		arg.Blueprint,
		arg.Spec,
		arg.TenantID,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Environment,
		&i.Blueprint,
		&i.Status,
		&i.Spec,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const deleteEnvironment = `-- name: DeleteEnvironment :exec
delete from environments where id = $1
`

func (q *Queries) DeleteEnvironment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEnvironment, id)
	return err
}

const getEnvironment = `-- name: GetEnvironment :one
select id, name, environment, blueprint, status, spec, created_at, updated_at, tenant_id from environments where id = $1
`

func (q *Queries) GetEnvironment(ctx context.Context, id uuid.UUID) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironment, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Environment,
		&i.Blueprint,
		&i.Status,
		&i.Spec,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const getEnvironmentByName = `-- name: GetEnvironmentByName :one
select id, name, environment, blueprint, status, spec, created_at, updated_at, tenant_id from environments where name = $1 and environment = $2
`

type GetEnvironmentByNameParams struct {
	Name        string `json:"name"`
	Environment string `json:"environment"`
}

func (q *Queries) GetEnvironmentByName(ctx context.Context, arg GetEnvironmentByNameParams) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByName, arg.Name, arg.Environment)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Environment,
		&i.Blueprint,
		&i.Status,
		&i.Spec,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const listEnvironments = `-- name: ListEnvironments :many
select id, name, environment, blueprint, status, spec, created_at, updated_at, tenant_id from environments order by created_at desc
`

func (q *Queries) ListEnvironments(ctx context.Context) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Environment{}
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Environment,
			&i.Blueprint,
			&i.Status,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnvironmentStatus = `-- name: UpdateEnvironmentStatus :one
update environments
set status = $2, updated_at = now()
where id = $1
returning id, name, environment, blueprint, status, spec, created_at, updated_at, tenant_id
`

type UpdateEnvironmentStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateEnvironmentStatus(ctx context.Context, arg UpdateEnvironmentStatusParams) (Environment, error) {
	row := q.db.QueryRow(ctx, updateEnvironmentStatus, arg.ID, arg.Status)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Environment,
		&i.Blueprint,
		&i.Status,
		&i.Spec,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}
