// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
insert into jobs (cluster_id, operation, status)
values ($1, $2, 'queued')
returning id, cluster_id, operation, status, river_job_id, error, started_at, finished_at, created_at
`

type CreateJobParams struct {
	ClusterID pgtype.UUID `json:"cluster_id"`
	Operation string      `json:"operation"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob, arg.ClusterID, arg.Operation)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Operation,
		&i.Status,
		&i.RiverJobID,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
select id, cluster_id, operation, status, river_job_id, error, started_at, finished_at, created_at from jobs where id = $1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Operation,
		&i.Status,
		&i.RiverJobID,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listJobsByCluster = `-- name: ListJobsByCluster :many
select id, cluster_id, operation, status, river_job_id, error, started_at, finished_at, created_at from jobs where cluster_id = $1 order by created_at desc
`

func (q *Queries) ListJobsByCluster(ctx context.Context, clusterID pgtype.UUID) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByCluster, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.Operation,
			&i.Status,
			&i.RiverJobID,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobFinished = `-- name: MarkJobFinished :one
update jobs
set status = $2, error = $3, finished_at = now()
where id = $1
returning id, cluster_id, operation, status, river_job_id, error, started_at, finished_at, created_at
`

type MarkJobFinishedParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
	Error  *string   `json:"error"`
}

func (q *Queries) MarkJobFinished(ctx context.Context, arg MarkJobFinishedParams) (Job, error) {
	row := q.db.QueryRow(ctx, markJobFinished, arg.ID, arg.Status, arg.Error)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Operation,
		&i.Status,
		&i.RiverJobID,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markJobRunning = `-- name: MarkJobRunning :one
update jobs
set status = 'running', river_job_id = $2, started_at = now()
where id = $1
returning id, cluster_id, operation, status, river_job_id, error, started_at, finished_at, created_at
`

type MarkJobRunningParams struct {
	ID         uuid.UUID `json:"id"`
	RiverJobID *int64    `json:"river_job_id"`
}

func (q *Queries) MarkJobRunning(ctx context.Context, arg MarkJobRunningParams) (Job, error) {
	row := q.db.QueryRow(ctx, markJobRunning, arg.ID, arg.RiverJobID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Operation,
		&i.Status,
		&i.RiverJobID,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}
