// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMCPGrant = `-- name: CreateMCPGrant :one
insert into mcp_grants (server_id, owner, expires_at, granted_by, tenant_id)
values ($1, $2, $3, $4, $5)
returning id, server_id, owner, status, expires_at, granted_by, tenant_id, created_at, revoked_at
`

type CreateMCPGrantParams struct {
	ServerID  uuid.UUID          `json:"server_id"`
	Owner     string             `json:"owner"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	GrantedBy string             `json:"granted_by"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
}

func (q *Queries) CreateMCPGrant(ctx context.Context, arg CreateMCPGrantParams) (McpGrant, error) {
	row := q.db.QueryRow(ctx, createMCPGrant,
		arg.ServerID,
		arg.Owner,
		arg.ExpiresAt,
		arg.GrantedBy,
		arg.TenantID,
	)
	var i McpGrant
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Owner,
		&i.Status,
		&i.ExpiresAt,
		&i.GrantedBy,
		&i.TenantID,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createMCPServer = `-- name: CreateMCPServer :one
insert into mcp_servers (name, transport, endpoint, description, risk_tier, allowed_tools, tenant_id)
values ($1, $2, $3, $4, $5, $6, $7)
returning id, name, transport, endpoint, description, risk_tier, allowed_tools, status, tenant_id, created_at, updated_at
`

type CreateMCPServerParams struct {
	Name         string      `json:"name"`
	Transport    string      `json:"transport"`
	Endpoint     string      `json:"endpoint"`
	Description  string      `json:"description"`
	RiskTier     string      `json:"risk_tier"`
	AllowedTools []byte      `json:"allowed_tools"`
	TenantID     pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) CreateMCPServer(ctx context.Context, arg CreateMCPServerParams) (McpServer, error) {
	row := q.db.QueryRow(ctx, createMCPServer,
		arg.Name,
		arg.Transport,
		arg.Endpoint,
		arg.Description,
		arg.RiskTier,
		arg.AllowedTools,
		arg.TenantID,
	)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Transport,
		&i.Endpoint,
		&i.Description,
		&i.RiskTier,
		&i.AllowedTools,
		&i.Status,
		&i.TenantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMCPServer = `-- name: DeleteMCPServer :exec
delete from mcp_servers where id = $1
`

func (q *Queries) DeleteMCPServer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMCPServer, id)
	return err
}

const findActiveMCPGrant = `-- name: FindActiveMCPGrant :one
select g.id, g.server_id, g.owner, g.status, g.expires_at, g.granted_by, g.tenant_id, g.created_at, g.revoked_at from mcp_grants g
where g.server_id = $1 and lower(g.owner) = lower($2) and g.status = 'active'
order by g.created_at desc
limit 1
`

type FindActiveMCPGrantParams struct {
	ServerID uuid.UUID `json:"server_id"`
	Lower    string    `json:"lower"`
}

func (q *Queries) FindActiveMCPGrant(ctx context.Context, arg FindActiveMCPGrantParams) (McpGrant, error) {
	row := q.db.QueryRow(ctx, findActiveMCPGrant, arg.ServerID, arg.Lower)
	var i McpGrant
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Owner,
		&i.Status,
		&i.ExpiresAt,
		&i.GrantedBy,
		&i.TenantID,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getMCPServerByName = `-- name: GetMCPServerByName :one
select id, name, transport, endpoint, description, risk_tier, allowed_tools, status, tenant_id, created_at, updated_at from mcp_servers where name = $1
`

func (q *Queries) GetMCPServerByName(ctx context.Context, name string) (McpServer, error) {
	row := q.db.QueryRow(ctx, getMCPServerByName, name)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Transport,
		&i.Endpoint,
		&i.Description,
		&i.RiskTier,
		&i.AllowedTools,
		&i.Status,
		&i.TenantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMCPGrants = `-- name: ListMCPGrants :many
select g.id, g.server_id, g.owner, g.status, g.expires_at, g.granted_by, g.tenant_id, g.created_at, g.revoked_at, s.name as server_name, s.risk_tier as server_risk_tier
from mcp_grants g
join mcp_servers s on s.id = g.server_id
order by g.created_at desc
`

type ListMCPGrantsRow struct {
	ID             uuid.UUID          `json:"id"`
	ServerID       uuid.UUID          `json:"server_id"`
	Owner          string             `json:"owner"`
	Status         string             `json:"status"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	GrantedBy      string             `json:"granted_by"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	CreatedAt      time.Time          `json:"created_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
	ServerName     string             `json:"server_name"`
	ServerRiskTier string             `json:"server_risk_tier"`
}

func (q *Queries) ListMCPGrants(ctx context.Context) ([]ListMCPGrantsRow, error) {
	rows, err := q.db.Query(ctx, listMCPGrants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMCPGrantsRow{}
	for rows.Next() {
		var i ListMCPGrantsRow
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Owner,
			&i.Status,
			&i.ExpiresAt,
			&i.GrantedBy,
			&i.TenantID,
			&i.CreatedAt,
			&i.RevokedAt,
			&i.ServerName,
			&i.ServerRiskTier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMCPServers = `-- name: ListMCPServers :many
select id, name, transport, endpoint, description, risk_tier, allowed_tools, status, tenant_id, created_at, updated_at from mcp_servers order by created_at desc
`

func (q *Queries) ListMCPServers(ctx context.Context) ([]McpServer, error) {
	rows, err := q.db.Query(ctx, listMCPServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []McpServer{}
	for rows.Next() {
		var i McpServer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Transport,
			&i.Endpoint,
			&i.Description,
			&i.RiskTier,
			&i.AllowedTools,
			&i.Status,
			&i.TenantID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeMCPGrant = `-- name: RevokeMCPGrant :one
update mcp_grants set status = 'revoked', revoked_at = now()
where id = $1
returning id, server_id, owner, status, expires_at, granted_by, tenant_id, created_at, revoked_at
`

func (q *Queries) RevokeMCPGrant(ctx context.Context, id uuid.UUID) (McpGrant, error) {
	row := q.db.QueryRow(ctx, revokeMCPGrant, id)
	var i McpGrant
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Owner,
		&i.Status,
		&i.ExpiresAt,
		&i.GrantedBy,
		&i.TenantID,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const updateMCPServerStatus = `-- name: UpdateMCPServerStatus :one
update mcp_servers set status = $2, updated_at = now() where id = $1 returning id, name, transport, endpoint, description, risk_tier, allowed_tools, status, tenant_id, created_at, updated_at
`

type UpdateMCPServerStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateMCPServerStatus(ctx context.Context, arg UpdateMCPServerStatusParams) (McpServer, error) {
	row := q.db.QueryRow(ctx, updateMCPServerStatus, arg.ID, arg.Status)
	var i McpServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Transport,
		&i.Endpoint,
		&i.Description,
		&i.RiskTier,
		&i.AllowedTools,
		&i.Status,
		&i.TenantID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
