// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AiAccessPolicy struct {
	ID        uuid.UUID   `json:"id"`
	Name      string      `json:"name"`
	TenantID  pgtype.UUID `json:"tenant_id"`
	Rules     []byte      `json:"rules"`
	Status    string      `json:"status"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type AiAuditEvent struct {
	ID          uuid.UUID   `json:"id"`
	Actor       string      `json:"actor"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	SubjectType string      `json:"subject_type"`
	SubjectID   pgtype.UUID `json:"subject_id"`
	Action      string      `json:"action"`
	Message     string      `json:"message"`
	Fields      []byte      `json:"fields"`
	CreatedAt   time.Time   `json:"created_at"`
}

type AiBudget struct {
	ID               uuid.UUID   `json:"id"`
	TenantID         pgtype.UUID `json:"tenant_id"`
	Scope            string      `json:"scope"`
	ScopeRef         string      `json:"scope_ref"`
	LimitUsd         float64     `json:"limit_usd"`
	Period           string      `json:"period"`
	SoftThresholdPct int32       `json:"soft_threshold_pct"`
	HardThresholdPct int32       `json:"hard_threshold_pct"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
}

type AiModelCatalog struct {
	ID          uuid.UUID `json:"id"`
	ProviderID  uuid.UUID `json:"provider_id"`
	Model       string    `json:"model"`
	DisplayName string    `json:"display_name"`
	Modality    string    `json:"modality"`
	Status      string    `json:"status"`
	Metadata    []byte    `json:"metadata"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type AiProvider struct {
	ID        uuid.UUID   `json:"id"`
	Name      string      `json:"name"`
	Type      string      `json:"type"`
	Config    []byte      `json:"config"`
	Status    string      `json:"status"`
	TenantID  pgtype.UUID `json:"tenant_id"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type AiProviderCredential struct {
	ID                   uuid.UUID          `json:"id"`
	ProviderID           uuid.UUID          `json:"provider_id"`
	SecretRef            string             `json:"secret_ref"`
	Scopes               []string           `json:"scopes"`
	RotationDueAt        pgtype.Timestamptz `json:"rotation_due_at"`
	LastValidatedAt      pgtype.Timestamptz `json:"last_validated_at"`
	LastValidationStatus string             `json:"last_validation_status"`
	CreatedAt            time.Time          `json:"created_at"`
}

type AiQuota struct {
	ID            uuid.UUID   `json:"id"`
	ServiceID     pgtype.UUID `json:"service_id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
	Metric        string      `json:"metric"`
	LimitQuantity float64     `json:"limit_quantity"`
	Period        string      `json:"period"`
	Enforcement   string      `json:"enforcement"`
	CreatedAt     time.Time   `json:"created_at"`
}

type AiService struct {
	ID                    uuid.UUID `json:"id"`
	ProviderID            uuid.UUID `json:"provider_id"`
	Name                  string    `json:"name"`
	Slug                  string    `json:"slug"`
	Category              string    `json:"category"`
	Description           string    `json:"description"`
	RequestSchema         []byte    `json:"request_schema"`
	DefaultExpirationDays int32     `json:"default_expiration_days"`
	RequiresApproval      bool      `json:"requires_approval"`
	Status                string    `json:"status"`
	CreatedAt             time.Time `json:"created_at"`
	UpdatedAt             time.Time `json:"updated_at"`
}

type AiServiceInstance struct {
	ID               uuid.UUID          `json:"id"`
	ServiceID        uuid.UUID          `json:"service_id"`
	RequestID        pgtype.UUID        `json:"request_id"`
	ProviderAccessID string             `json:"provider_access_id"`
	Owner            string             `json:"owner"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	Workspace        string             `json:"workspace"`
	Status           string             `json:"status"`
	Spec             []byte             `json:"spec"`
	Observed         []byte             `json:"observed"`
	ProvisionedAt    pgtype.Timestamptz `json:"provisioned_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

type AiUsageRecord struct {
	ID          uuid.UUID   `json:"id"`
	InstanceID  pgtype.UUID `json:"instance_id"`
	ProviderID  uuid.UUID   `json:"provider_id"`
	PeriodStart time.Time   `json:"period_start"`
	PeriodEnd   time.Time   `json:"period_end"`
	Metric      string      `json:"metric"`
	Quantity    float64     `json:"quantity"`
	Unit        string      `json:"unit"`
	CostUsd     float64     `json:"cost_usd"`
	Raw         []byte      `json:"raw"`
	CreatedAt   time.Time   `json:"created_at"`
}

type Backup struct {
	ID            uuid.UUID   `json:"id"`
	ResourceKind  string      `json:"resource_kind"`
	ResourceName  string      `json:"resource_name"`
	Environment   string      `json:"environment"`
	Provider      string      `json:"provider"`
	SnapshotID    string      `json:"snapshot_id"`
	TofuWorkspace string      `json:"tofu_workspace"`
	Status        string      `json:"status"`
	TenantID      pgtype.UUID `json:"tenant_id"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

type Cluster struct {
	ID            uuid.UUID   `json:"id"`
	Name          string      `json:"name"`
	Environment   string      `json:"environment"`
	ProviderID    uuid.UUID   `json:"provider_id"`
	Status        string      `json:"status"`
	DesiredSpec   []byte      `json:"desired_spec"`
	ObservedState []byte      `json:"observed_state"`
	TofuWorkspace string      `json:"tofu_workspace"`
	KubeconfigRef *string     `json:"kubeconfig_ref"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	TenantID      pgtype.UUID `json:"tenant_id"`
}

type Environment struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Environment string      `json:"environment"`
	Blueprint   string      `json:"blueprint"`
	Status      string      `json:"status"`
	Spec        []byte      `json:"spec"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
	TenantID    pgtype.UUID `json:"tenant_id"`
}

type Job struct {
	ID         uuid.UUID          `json:"id"`
	ClusterID  pgtype.UUID        `json:"cluster_id"`
	Operation  string             `json:"operation"`
	Status     string             `json:"status"`
	RiverJobID *int64             `json:"river_job_id"`
	Error      *string            `json:"error"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

type McpGrant struct {
	ID        uuid.UUID          `json:"id"`
	ServerID  uuid.UUID          `json:"server_id"`
	Owner     string             `json:"owner"`
	Status    string             `json:"status"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	GrantedBy string             `json:"granted_by"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	CreatedAt time.Time          `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type McpServer struct {
	ID           uuid.UUID   `json:"id"`
	Name         string      `json:"name"`
	Transport    string      `json:"transport"`
	Endpoint     string      `json:"endpoint"`
	Description  string      `json:"description"`
	RiskTier     string      `json:"risk_tier"`
	AllowedTools []byte      `json:"allowed_tools"`
	Status       string      `json:"status"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type Node struct {
	ID        uuid.UUID `json:"id"`
	ClusterID uuid.UUID `json:"cluster_id"`
	Name      string    `json:"name"`
	Role      string    `json:"role"`
	IpAddress *string   `json:"ip_address"`
	VmMoid    *string   `json:"vm_moid"`
	Cpu       *int32    `json:"cpu"`
	MemoryMb  *int32    `json:"memory_mb"`
	DiskGb    *int32    `json:"disk_gb"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Provider struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	Type               string             `json:"type"`
	Config             []byte             `json:"config"`
	SecretRef          string             `json:"secret_ref"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	LastCheckStatus    string             `json:"last_check_status"`
	LastCheckMessage   string             `json:"last_check_message"`
	LastCheckLatencyMs int32              `json:"last_check_latency_ms"`
	LastCheckAt        pgtype.Timestamptz `json:"last_check_at"`
}

type Request struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Environment string      `json:"environment"`
	Requester   string      `json:"requester"`
	Kind        string      `json:"kind"`
	Provider    string      `json:"provider"`
	Blueprint   string      `json:"blueprint"`
	Spec        []byte      `json:"spec"`
	Status      string      `json:"status"`
	TicketRef   string      `json:"ticket_ref"`
	ResourceRef string      `json:"resource_ref"`
	DecidedBy   string      `json:"decided_by"`
	Reason      string      `json:"reason"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
	TenantID    pgtype.UUID `json:"tenant_id"`
}

type Resource struct {
	ID            uuid.UUID   `json:"id"`
	Name          string      `json:"name"`
	Environment   string      `json:"environment"`
	ProviderID    uuid.UUID   `json:"provider_id"`
	Kind          string      `json:"kind"`
	Status        string      `json:"status"`
	Spec          []byte      `json:"spec"`
	Observed      []byte      `json:"observed"`
	TofuWorkspace string      `json:"tofu_workspace"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
	TenantID      pgtype.UUID `json:"tenant_id"`
}

type Template struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Os           string    `json:"os"`
	OsVersion    string    `json:"os_version"`
	ProviderType string    `json:"provider_type"`
	CreatedAt    time.Time `json:"created_at"`
}

type Tenant struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID         uuid.UUID `json:"id"`
	Email      string    `json:"email"`
	TenantID   uuid.UUID `json:"tenant_id"`
	Role       string    `json:"role"`
	ApiKeyHash string    `json:"api_key_hash"`
	CreatedAt  time.Time `json:"created_at"`
}
