// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteNodesByCluster = `-- name: DeleteNodesByCluster :exec
delete from nodes where cluster_id = $1
`

func (q *Queries) DeleteNodesByCluster(ctx context.Context, clusterID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteNodesByCluster, clusterID)
	return err
}

const listNodesByCluster = `-- name: ListNodesByCluster :many
select id, cluster_id, name, role, ip_address, vm_moid, cpu, memory_mb, disk_gb, status, created_at, updated_at from nodes where cluster_id = $1 order by role, name
`

func (q *Queries) ListNodesByCluster(ctx context.Context, clusterID uuid.UUID) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodesByCluster, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.Name,
			&i.Role,
			&i.IpAddress,
			&i.VmMoid,
			&i.Cpu,
			&i.MemoryMb,
			&i.DiskGb,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNodeStatus = `-- name: UpdateNodeStatus :one
update nodes
set status = $2, updated_at = now()
where id = $1
returning id, cluster_id, name, role, ip_address, vm_moid, cpu, memory_mb, disk_gb, status, created_at, updated_at
`

type UpdateNodeStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateNodeStatus(ctx context.Context, arg UpdateNodeStatusParams) (Node, error) {
	row := q.db.QueryRow(ctx, updateNodeStatus, arg.ID, arg.Status)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Name,
		&i.Role,
		&i.IpAddress,
		&i.VmMoid,
		&i.Cpu,
		&i.MemoryMb,
		&i.DiskGb,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNode = `-- name: UpsertNode :one
insert into nodes (cluster_id, name, role, ip_address, vm_moid, cpu, memory_mb, disk_gb, status)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
on conflict (cluster_id, name) do update
set role = excluded.role,
    ip_address = excluded.ip_address,
    vm_moid = excluded.vm_moid,
    cpu = excluded.cpu,
    memory_mb = excluded.memory_mb,
    disk_gb = excluded.disk_gb,
    status = excluded.status,
    updated_at = now()
returning id, cluster_id, name, role, ip_address, vm_moid, cpu, memory_mb, disk_gb, status, created_at, updated_at
`

type UpsertNodeParams struct {
	ClusterID uuid.UUID `json:"cluster_id"`
	Name      string    `json:"name"`
	Role      string    `json:"role"`
	IpAddress *string   `json:"ip_address"`
	VmMoid    *string   `json:"vm_moid"`
	Cpu       *int32    `json:"cpu"`
	MemoryMb  *int32    `json:"memory_mb"`
	DiskGb    *int32    `json:"disk_gb"`
	Status    string    `json:"status"`
}

func (q *Queries) UpsertNode(ctx context.Context, arg UpsertNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, upsertNode,
		arg.ClusterID,
		arg.Name,
		arg.Role,
		arg.IpAddress,
		arg.VmMoid,
		arg.Cpu,
		arg.MemoryMb,
		arg.DiskGb,
		arg.Status,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Name,
		&i.Role,
		&i.IpAddress,
		&i.VmMoid,
		&i.Cpu,
		&i.MemoryMb,
		&i.DiskGb,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
