// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: providers.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countClustersByProvider = `-- name: CountClustersByProvider :one
select count(*) from clusters where provider_id = $1
`

func (q *Queries) CountClustersByProvider(ctx context.Context, providerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countClustersByProvider, providerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countResourcesByProvider = `-- name: CountResourcesByProvider :one
select count(*) from resources where provider_id = $1
`

func (q *Queries) CountResourcesByProvider(ctx context.Context, providerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countResourcesByProvider, providerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProvider = `-- name: CreateProvider :one
insert into providers (name, type, config, secret_ref)
values ($1, $2, $3, $4)
returning id, name, type, config, secret_ref, created_at, updated_at, last_check_status, last_check_message, last_check_latency_ms, last_check_at
`

type CreateProviderParams struct {
	Name      string `json:"name"`
	Type      string `json:"type"`
	Config    []byte `json:"config"`
	SecretRef string `json:"secret_ref"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.SecretRef,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.SecretRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastCheckStatus,
		&i.LastCheckMessage,
		&i.LastCheckLatencyMs,
		&i.LastCheckAt,
	)
	return i, err
}

const deleteProvider = `-- name: DeleteProvider :exec
delete from providers where id = $1
`

func (q *Queries) DeleteProvider(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProvider, id)
	return err
}

const getProvider = `-- name: GetProvider :one
select id, name, type, config, secret_ref, created_at, updated_at, last_check_status, last_check_message, last_check_latency_ms, last_check_at from providers where id = $1
`

func (q *Queries) GetProvider(ctx context.Context, id uuid.UUID) (Provider, error) {
	row := q.db.QueryRow(ctx, getProvider, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.SecretRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastCheckStatus,
		&i.LastCheckMessage,
		&i.LastCheckLatencyMs,
		&i.LastCheckAt,
	)
	return i, err
}

const getProviderByName = `-- name: GetProviderByName :one
select id, name, type, config, secret_ref, created_at, updated_at, last_check_status, last_check_message, last_check_latency_ms, last_check_at from providers where name = $1
`

func (q *Queries) GetProviderByName(ctx context.Context, name string) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderByName, name)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.SecretRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastCheckStatus,
		&i.LastCheckMessage,
		&i.LastCheckLatencyMs,
		&i.LastCheckAt,
	)
	return i, err
}

const listProviders = `-- name: ListProviders :many
select id, name, type, config, secret_ref, created_at, updated_at, last_check_status, last_check_message, last_check_latency_ms, last_check_at from providers order by created_at desc
`

func (q *Queries) ListProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.SecretRef,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastCheckStatus,
			&i.LastCheckMessage,
			&i.LastCheckLatencyMs,
			&i.LastCheckAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProvider = `-- name: UpdateProvider :one
update providers
set name = $2, type = $3, config = $4, secret_ref = $5, updated_at = now()
where id = $1
returning id, name, type, config, secret_ref, created_at, updated_at, last_check_status, last_check_message, last_check_latency_ms, last_check_at
`

type UpdateProviderParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Type      string    `json:"type"`
	Config    []byte    `json:"config"`
	SecretRef string    `json:"secret_ref"`
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProvider,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.SecretRef,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.SecretRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastCheckStatus,
		&i.LastCheckMessage,
		&i.LastCheckLatencyMs,
		&i.LastCheckAt,
	)
	return i, err
}

const updateProviderHealth = `-- name: UpdateProviderHealth :one
update providers
set last_check_status = $2,
    last_check_message = $3,
    last_check_latency_ms = $4,
    last_check_at = now()
where id = $1
returning id, name, type, config, secret_ref, created_at, updated_at, last_check_status, last_check_message, last_check_latency_ms, last_check_at
`

type UpdateProviderHealthParams struct {
	ID                 uuid.UUID `json:"id"`
	LastCheckStatus    string    `json:"last_check_status"`
	LastCheckMessage   string    `json:"last_check_message"`
	LastCheckLatencyMs int32     `json:"last_check_latency_ms"`
}

func (q *Queries) UpdateProviderHealth(ctx context.Context, arg UpdateProviderHealthParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProviderHealth,
		arg.ID,
		arg.LastCheckStatus,
		arg.LastCheckMessage,
		arg.LastCheckLatencyMs,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.SecretRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastCheckStatus,
		&i.LastCheckMessage,
		&i.LastCheckLatencyMs,
		&i.LastCheckAt,
	)
	return i, err
}
