// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountActiveAIInstancesByProvider(ctx context.Context, providerID uuid.UUID) (int64, error)
	CountClustersByProvider(ctx context.Context, providerID uuid.UUID) (int64, error)
	CountResourcesByProvider(ctx context.Context, providerID uuid.UUID) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAIAccessPolicy(ctx context.Context, arg CreateAIAccessPolicyParams) (AiAccessPolicy, error)
	CreateAIAuditEvent(ctx context.Context, arg CreateAIAuditEventParams) (AiAuditEvent, error)
	CreateAIBudget(ctx context.Context, arg CreateAIBudgetParams) (AiBudget, error)
	CreateAIProvider(ctx context.Context, arg CreateAIProviderParams) (AiProvider, error)
	CreateAIProviderCredential(ctx context.Context, arg CreateAIProviderCredentialParams) (AiProviderCredential, error)
	CreateAIQuota(ctx context.Context, arg CreateAIQuotaParams) (AiQuota, error)
	CreateAIService(ctx context.Context, arg CreateAIServiceParams) (AiService, error)
	CreateAIServiceInstance(ctx context.Context, arg CreateAIServiceInstanceParams) (AiServiceInstance, error)
	CreateAIUsageRecord(ctx context.Context, arg CreateAIUsageRecordParams) (AiUsageRecord, error)
	CreateBackup(ctx context.Context, arg CreateBackupParams) (Backup, error)
	CreateCluster(ctx context.Context, arg CreateClusterParams) (Cluster, error)
	CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error)
	CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error)
	CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error)
	CreateTenant(ctx context.Context, name string) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DecideRequest(ctx context.Context, arg DecideRequestParams) (Request, error)
	DeleteAIAccessPolicy(ctx context.Context, id uuid.UUID) error
	DeleteAIBudget(ctx context.Context, id uuid.UUID) error
	DeleteAIProvider(ctx context.Context, id uuid.UUID) error
	DeleteAIQuota(ctx context.Context, id uuid.UUID) error
	DeleteAIServiceInstancesByProvider(ctx context.Context, providerID uuid.UUID) error
	DeleteCluster(ctx context.Context, id uuid.UUID) error
	DeleteEnvironment(ctx context.Context, id uuid.UUID) error
	DeleteNodesByCluster(ctx context.Context, clusterID uuid.UUID) error
	DeleteProvider(ctx context.Context, id uuid.UUID) error
	DeleteResource(ctx context.Context, id uuid.UUID) error
	ExpireAIServiceInstances(ctx context.Context) ([]AiServiceInstance, error)
	FindAIUsageRecordByImportKey(ctx context.Context, arg FindAIUsageRecordByImportKeyParams) (AiUsageRecord, error)
	GetAIBudget(ctx context.Context, id uuid.UUID) (AiBudget, error)
	GetAIProvider(ctx context.Context, id uuid.UUID) (AiProvider, error)
	GetAIProviderByName(ctx context.Context, name string) (AiProvider, error)
	GetAIProviderCredentialByProvider(ctx context.Context, providerID uuid.UUID) (AiProviderCredential, error)
	GetAIService(ctx context.Context, id uuid.UUID) (GetAIServiceRow, error)
	GetAIServiceBySlug(ctx context.Context, slug string) (GetAIServiceBySlugRow, error)
	GetAIServiceInstance(ctx context.Context, id uuid.UUID) (AiServiceInstance, error)
	GetBackup(ctx context.Context, id uuid.UUID) (Backup, error)
	GetCluster(ctx context.Context, id uuid.UUID) (Cluster, error)
	GetClusterByName(ctx context.Context, arg GetClusterByNameParams) (Cluster, error)
	GetEnvironment(ctx context.Context, id uuid.UUID) (Environment, error)
	GetEnvironmentByName(ctx context.Context, arg GetEnvironmentByNameParams) (Environment, error)
	GetJob(ctx context.Context, id uuid.UUID) (Job, error)
	GetProvider(ctx context.Context, id uuid.UUID) (Provider, error)
	GetProviderByName(ctx context.Context, name string) (Provider, error)
	GetRequest(ctx context.Context, id uuid.UUID) (Request, error)
	GetRequestByName(ctx context.Context, arg GetRequestByNameParams) (Request, error)
	GetResource(ctx context.Context, id uuid.UUID) (Resource, error)
	GetResourceByName(ctx context.Context, arg GetResourceByNameParams) (Resource, error)
	GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetTenantByName(ctx context.Context, name string) (Tenant, error)
	GetUserByAPIKeyHash(ctx context.Context, apiKeyHash string) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListAIAccessPolicies(ctx context.Context) ([]AiAccessPolicy, error)
	ListAIAuditEvents(ctx context.Context, limit int32) ([]AiAuditEvent, error)
	ListAIBudgets(ctx context.Context) ([]AiBudget, error)
	ListAIExpiringInstances(ctx context.Context, dollar_1 int32) ([]ListAIExpiringInstancesRow, error)
	ListAIModelCatalog(ctx context.Context) ([]ListAIModelCatalogRow, error)
	ListAIProviderCredentials(ctx context.Context) ([]AiProviderCredential, error)
	ListAIProviders(ctx context.Context) ([]AiProvider, error)
	ListAIQuotas(ctx context.Context) ([]AiQuota, error)
	ListAIServiceInstances(ctx context.Context) ([]ListAIServiceInstancesRow, error)
	ListAIServices(ctx context.Context) ([]ListAIServicesRow, error)
	ListAIUsageRecords(ctx context.Context) ([]ListAIUsageRecordsRow, error)
	ListBackups(ctx context.Context) ([]Backup, error)
	ListClusters(ctx context.Context) ([]Cluster, error)
	ListClustersByProvider(ctx context.Context, providerID uuid.UUID) ([]Cluster, error)
	ListEnvironments(ctx context.Context) ([]Environment, error)
	ListJobsByCluster(ctx context.Context, clusterID pgtype.UUID) ([]Job, error)
	ListNodesByCluster(ctx context.Context, clusterID uuid.UUID) ([]Node, error)
	ListProviders(ctx context.Context) ([]Provider, error)
	ListRequests(ctx context.Context) ([]Request, error)
	ListResources(ctx context.Context) ([]Resource, error)
	ListResourcesByKind(ctx context.Context, kind string) ([]Resource, error)
	ListTenants(ctx context.Context) ([]Tenant, error)
	ListUsers(ctx context.Context) ([]User, error)
	MarkJobFinished(ctx context.Context, arg MarkJobFinishedParams) (Job, error)
	MarkJobRunning(ctx context.Context, arg MarkJobRunningParams) (Job, error)
	RevokeAIServiceInstance(ctx context.Context, id uuid.UUID) (AiServiceInstance, error)
	SetBackupResult(ctx context.Context, arg SetBackupResultParams) (Backup, error)
	SetRequestResource(ctx context.Context, arg SetRequestResourceParams) (Request, error)
	SetRequestTicket(ctx context.Context, arg SetRequestTicketParams) (Request, error)
	UpdateAIProvider(ctx context.Context, arg UpdateAIProviderParams) (AiProvider, error)
	UpdateAIServiceInstanceStatus(ctx context.Context, arg UpdateAIServiceInstanceStatusParams) (AiServiceInstance, error)
	UpdateClusterSpec(ctx context.Context, arg UpdateClusterSpecParams) (Cluster, error)
	UpdateClusterState(ctx context.Context, arg UpdateClusterStateParams) (Cluster, error)
	UpdateClusterStatus(ctx context.Context, arg UpdateClusterStatusParams) (Cluster, error)
	UpdateEnvironmentStatus(ctx context.Context, arg UpdateEnvironmentStatusParams) (Environment, error)
	UpdateNodeStatus(ctx context.Context, arg UpdateNodeStatusParams) (Node, error)
	UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error)
	UpdateProviderHealth(ctx context.Context, arg UpdateProviderHealthParams) (Provider, error)
	UpdateRequestStatus(ctx context.Context, arg UpdateRequestStatusParams) (Request, error)
	UpdateResourceObserved(ctx context.Context, arg UpdateResourceObservedParams) (Resource, error)
	UpdateResourceSpec(ctx context.Context, arg UpdateResourceSpecParams) (Resource, error)
	UpdateResourceStatus(ctx context.Context, arg UpdateResourceStatusParams) (Resource, error)
	UpsertAIModelCatalog(ctx context.Context, arg UpsertAIModelCatalogParams) (AiModelCatalog, error)
	UpsertNode(ctx context.Context, arg UpsertNodeParams) (Node, error)
}

var _ Querier = (*Queries)(nil)
