// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: requests.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRequest = `-- name: CreateRequest :one
insert into requests (name, environment, requester, kind, provider, blueprint, spec, tenant_id)
values ($1, $2, $3, $4, $5, $6, $7, $8)
returning id, name, environment, requester, kind, provider, blueprint, spec, status, ticket_ref, resource_ref, decided_by, reason, created_at, updated_at, tenant_id
`

type CreateRequestParams struct {
	Name        string      `json:"name"`
	Environment string      `json:"environment"`
	Requester   string      `json:"requester"`
	Kind        string      `json:"kind"`
	Provider    string      `json:"provider"`
	Blueprint   string      `json:"blueprint"`
	Spec        []byte      `json:"spec"`
	TenantID    pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error) {
	row := q.db.QueryRow(ctx, createRequest,
		arg.Name,
		arg.Environment,
		arg.Requester,
		arg.Kind,
		arg.Provider,
		arg.Blueprint,
		arg.Spec,
		arg.TenantID,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Environment,
		&i.Requester,
		&i.Kind,
		&i.Provider,
		&i.Blueprint,
		&i.Spec,
		&i.Status,
		&i.TicketRef,
		&i.ResourceRef,
		&i.DecidedBy,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const decideRequest = `-- name: DecideRequest :one
update requests
set status = $2, decided_by = $3, reason = $4, updated_at = now()
where id = $1
returning id, name, environment, requester, kind, provider, blueprint, spec, status, ticket_ref, resource_ref, decided_by, reason, created_at, updated_at, tenant_id
`

type DecideRequestParams struct {
	ID        uuid.UUID `json:"id"`
	Status    string    `json:"status"`
	DecidedBy string    `json:"decided_by"`
	Reason    string    `json:"reason"`
}

func (q *Queries) DecideRequest(ctx context.Context, arg DecideRequestParams) (Request, error) {
	row := q.db.QueryRow(ctx, decideRequest,
		arg.ID,
		arg.Status,
		arg.DecidedBy,
		arg.Reason,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Environment,
		&i.Requester,
		&i.Kind,
		&i.Provider,
		&i.Blueprint,
		&i.Spec,
		&i.Status,
		&i.TicketRef,
		&i.ResourceRef,
		&i.DecidedBy,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const getRequest = `-- name: GetRequest :one
select id, name, environment, requester, kind, provider, blueprint, spec, status, ticket_ref, resource_ref, decided_by, reason, created_at, updated_at, tenant_id from requests where id = $1
`

func (q *Queries) GetRequest(ctx context.Context, id uuid.UUID) (Request, error) {
	row := q.db.QueryRow(ctx, getRequest, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Environment,
		&i.Requester,
		&i.Kind,
		&i.Provider,
		&i.Blueprint,
		&i.Spec,
		&i.Status,
		&i.TicketRef,
		&i.ResourceRef,
		&i.DecidedBy,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const getRequestByName = `-- name: GetRequestByName :one
select id, name, environment, requester, kind, provider, blueprint, spec, status, ticket_ref, resource_ref, decided_by, reason, created_at, updated_at, tenant_id from requests where name = $1 and environment = $2
`

type GetRequestByNameParams struct {
	Name        string `json:"name"`
	Environment string `json:"environment"`
}

func (q *Queries) GetRequestByName(ctx context.Context, arg GetRequestByNameParams) (Request, error) {
	row := q.db.QueryRow(ctx, getRequestByName, arg.Name, arg.Environment)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Environment,
		&i.Requester,
		&i.Kind,
		&i.Provider,
		&i.Blueprint,
		&i.Spec,
		&i.Status,
		&i.TicketRef,
		&i.ResourceRef,
		&i.DecidedBy,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const listRequests = `-- name: ListRequests :many
select id, name, environment, requester, kind, provider, blueprint, spec, status, ticket_ref, resource_ref, decided_by, reason, created_at, updated_at, tenant_id from requests order by created_at desc
`

func (q *Queries) ListRequests(ctx context.Context) ([]Request, error) {
	rows, err := q.db.Query(ctx, listRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Environment,
			&i.Requester,
			&i.Kind,
			&i.Provider,
			&i.Blueprint,
			&i.Spec,
			&i.Status,
			&i.TicketRef,
			&i.ResourceRef,
			&i.DecidedBy,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRequestResource = `-- name: SetRequestResource :one
update requests
set resource_ref = $2, status = $3, updated_at = now()
where id = $1
returning id, name, environment, requester, kind, provider, blueprint, spec, status, ticket_ref, resource_ref, decided_by, reason, created_at, updated_at, tenant_id
`

type SetRequestResourceParams struct {
	ID          uuid.UUID `json:"id"`
	ResourceRef string    `json:"resource_ref"`
	Status      string    `json:"status"`
}

func (q *Queries) SetRequestResource(ctx context.Context, arg SetRequestResourceParams) (Request, error) {
	row := q.db.QueryRow(ctx, setRequestResource, arg.ID, arg.ResourceRef, arg.Status)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Environment,
		&i.Requester,
		&i.Kind,
		&i.Provider,
		&i.Blueprint,
		&i.Spec,
		&i.Status,
		&i.TicketRef,
		&i.ResourceRef,
		&i.DecidedBy,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const setRequestTicket = `-- name: SetRequestTicket :one
update requests
set ticket_ref = $2, updated_at = now()
where id = $1
returning id, name, environment, requester, kind, provider, blueprint, spec, status, ticket_ref, resource_ref, decided_by, reason, created_at, updated_at, tenant_id
`

type SetRequestTicketParams struct {
	ID        uuid.UUID `json:"id"`
	TicketRef string    `json:"ticket_ref"`
}

func (q *Queries) SetRequestTicket(ctx context.Context, arg SetRequestTicketParams) (Request, error) {
	row := q.db.QueryRow(ctx, setRequestTicket, arg.ID, arg.TicketRef)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Environment,
		&i.Requester,
		&i.Kind,
		&i.Provider,
		&i.Blueprint,
		&i.Spec,
		&i.Status,
		&i.TicketRef,
		&i.ResourceRef,
		&i.DecidedBy,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const updateRequestStatus = `-- name: UpdateRequestStatus :one
update requests
set status = $2, updated_at = now()
where id = $1
returning id, name, environment, requester, kind, provider, blueprint, spec, status, ticket_ref, resource_ref, decided_by, reason, created_at, updated_at, tenant_id
`

type UpdateRequestStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateRequestStatus(ctx context.Context, arg UpdateRequestStatusParams) (Request, error) {
	row := q.db.QueryRow(ctx, updateRequestStatus, arg.ID, arg.Status)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Environment,
		&i.Requester,
		&i.Kind,
		&i.Provider,
		&i.Blueprint,
		&i.Spec,
		&i.Status,
		&i.TicketRef,
		&i.ResourceRef,
		&i.DecidedBy,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}
