// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createResource = `-- name: CreateResource :one
insert into resources (name, environment, provider_id, kind, spec, tofu_workspace, tenant_id)
values ($1, $2, $3, $4, $5, $6, $7)
returning id, name, environment, provider_id, kind, status, spec, observed, tofu_workspace, created_at, updated_at, tenant_id
`

type CreateResourceParams struct {
	Name          string      `json:"name"`
	Environment   string      `json:"environment"`
	ProviderID    uuid.UUID   `json:"provider_id"`
	Kind          string      `json:"kind"`
	Spec          []byte      `json:"spec"`
	TofuWorkspace string      `json:"tofu_workspace"`
	TenantID      pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, createResource,
		arg.Name,
		arg.Environment,
		arg.ProviderID,
		arg.Kind,
		arg.Spec,
		arg.TofuWorkspace,
		arg.TenantID,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Environment,
		&i.ProviderID,
		&i.Kind,
		&i.Status,
		&i.Spec,
		&i.Observed,
		&i.TofuWorkspace,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const deleteResource = `-- name: DeleteResource :exec
delete from resources where id = $1
`

func (q *Queries) DeleteResource(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteResource, id)
	return err
}

const getResource = `-- name: GetResource :one
select id, name, environment, provider_id, kind, status, spec, observed, tofu_workspace, created_at, updated_at, tenant_id from resources where id = $1
`

func (q *Queries) GetResource(ctx context.Context, id uuid.UUID) (Resource, error) {
	row := q.db.QueryRow(ctx, getResource, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Environment,
		&i.ProviderID,
		&i.Kind,
		&i.Status,
		&i.Spec,
		&i.Observed,
		&i.TofuWorkspace,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const getResourceByName = `-- name: GetResourceByName :one
select id, name, environment, provider_id, kind, status, spec, observed, tofu_workspace, created_at, updated_at, tenant_id from resources where name = $1 and environment = $2
`

type GetResourceByNameParams struct {
	Name        string `json:"name"`
	Environment string `json:"environment"`
}

func (q *Queries) GetResourceByName(ctx context.Context, arg GetResourceByNameParams) (Resource, error) {
	row := q.db.QueryRow(ctx, getResourceByName, arg.Name, arg.Environment)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Environment,
		&i.ProviderID,
		&i.Kind,
		&i.Status,
		&i.Spec,
		&i.Observed,
		&i.TofuWorkspace,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const listResources = `-- name: ListResources :many
select id, name, environment, provider_id, kind, status, spec, observed, tofu_workspace, created_at, updated_at, tenant_id from resources order by created_at desc
`

func (q *Queries) ListResources(ctx context.Context) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Environment,
			&i.ProviderID,
			&i.Kind,
			&i.Status,
			&i.Spec,
			&i.Observed,
			&i.TofuWorkspace,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByKind = `-- name: ListResourcesByKind :many
select id, name, environment, provider_id, kind, status, spec, observed, tofu_workspace, created_at, updated_at, tenant_id from resources where kind = $1 order by created_at desc
`

func (q *Queries) ListResourcesByKind(ctx context.Context, kind string) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResourcesByKind, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Environment,
			&i.ProviderID,
			&i.Kind,
			&i.Status,
			&i.Spec,
			&i.Observed,
			&i.TofuWorkspace,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TenantID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResourceObserved = `-- name: UpdateResourceObserved :one
update resources
set observed = $2, status = $3, updated_at = now()
where id = $1
returning id, name, environment, provider_id, kind, status, spec, observed, tofu_workspace, created_at, updated_at, tenant_id
`

type UpdateResourceObservedParams struct {
	ID       uuid.UUID `json:"id"`
	Observed []byte    `json:"observed"`
	Status   string    `json:"status"`
}

func (q *Queries) UpdateResourceObserved(ctx context.Context, arg UpdateResourceObservedParams) (Resource, error) {
	row := q.db.QueryRow(ctx, updateResourceObserved, arg.ID, arg.Observed, arg.Status)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Environment,
		&i.ProviderID,
		&i.Kind,
		&i.Status,
		&i.Spec,
		&i.Observed,
		&i.TofuWorkspace,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const updateResourceSpec = `-- name: UpdateResourceSpec :one
update resources
set spec = $2, status = $3, updated_at = now()
where id = $1
returning id, name, environment, provider_id, kind, status, spec, observed, tofu_workspace, created_at, updated_at, tenant_id
`

type UpdateResourceSpecParams struct {
	ID     uuid.UUID `json:"id"`
	Spec   []byte    `json:"spec"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateResourceSpec(ctx context.Context, arg UpdateResourceSpecParams) (Resource, error) {
	row := q.db.QueryRow(ctx, updateResourceSpec, arg.ID, arg.Spec, arg.Status)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Environment,
		&i.ProviderID,
		&i.Kind,
		&i.Status,
		&i.Spec,
		&i.Observed,
		&i.TofuWorkspace,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}

const updateResourceStatus = `-- name: UpdateResourceStatus :one
update resources
set status = $2, updated_at = now()
where id = $1
returning id, name, environment, provider_id, kind, status, spec, observed, tofu_workspace, created_at, updated_at, tenant_id
`

type UpdateResourceStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateResourceStatus(ctx context.Context, arg UpdateResourceStatusParams) (Resource, error) {
	row := q.db.QueryRow(ctx, updateResourceStatus, arg.ID, arg.Status)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Environment,
		&i.ProviderID,
		&i.Kind,
		&i.Status,
		&i.Spec,
		&i.Observed,
		&i.TofuWorkspace,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}
