// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
select count(*) from users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTenant = `-- name: CreateTenant :one
insert into tenants (name) values ($1) returning id, name, created_at
`

func (q *Queries) CreateTenant(ctx context.Context, name string) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, name)
	var i Tenant
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createUser = `-- name: CreateUser :one
insert into users (email, tenant_id, role, api_key_hash)
values ($1, $2, $3, $4)
returning id, email, tenant_id, role, api_key_hash, created_at
`

type CreateUserParams struct {
	Email      string    `json:"email"`
	TenantID   uuid.UUID `json:"tenant_id"`
	Role       string    `json:"role"`
	ApiKeyHash string    `json:"api_key_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.TenantID,
		arg.Role,
		arg.ApiKeyHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TenantID,
		&i.Role,
		&i.ApiKeyHash,
		&i.CreatedAt,
	)
	return i, err
}

const getTenant = `-- name: GetTenant :one
select id, name, created_at from tenants where id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getTenantByName = `-- name: GetTenantByName :one
select id, name, created_at from tenants where name = $1
`

func (q *Queries) GetTenantByName(ctx context.Context, name string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByName, name)
	var i Tenant
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getUserByAPIKeyHash = `-- name: GetUserByAPIKeyHash :one
select id, email, tenant_id, role, api_key_hash, created_at from users where api_key_hash = $1
`

func (q *Queries) GetUserByAPIKeyHash(ctx context.Context, apiKeyHash string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAPIKeyHash, apiKeyHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TenantID,
		&i.Role,
		&i.ApiKeyHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, tenant_id, role, api_key_hash, created_at from users where email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.TenantID,
		&i.Role,
		&i.ApiKeyHash,
		&i.CreatedAt,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
select id, name, created_at from tenants order by created_at desc
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
select id, email, tenant_id, role, api_key_hash, created_at from users order by created_at desc
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.TenantID,
			&i.Role,
			&i.ApiKeyHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
